### PR TITLE
Feature/oauth callback

### PR DESCRIPTION
**Pull request by cr0**
should fix syncany/syncany#441

@binwiederhier, since you're the GUI guy, you might cleanup some of my messy code :D Also please try if it works as expected.

### CODE REVIEW

**Comment by binwiederhier** [comment]
Nicely done. :+1: As always a bit of feedback: The success case works very nicely, however, all the non-success cases seem to be largely unhandled.

(1) I've moved the start of the timeout (`waitForTokenResponse()`) to the button click event. Starting it right away makes no sense.

(2) While the change in (1) makes sense, we need to encounter for a user pressing the button mutiple times. Maybe deactivate it when it is clicked and disable a timer on the deactivated button ("Authorize (60)", "Authorize (59)", ...). Then showing the error and re-activating the button again. 

(3) When the time runs out, the button is deactivated and can never be clicked again. I've added another call to `asyncRetrieveOAuthUrlAndEnableAuthButton()` to the `TimeoutException` section, but that fails because the 6462 port cannot be rebound:

2015041901 31 01_selection_001

(4) In my opinion, any OAuth error should display an error message and kill all "waiting" threads, especially the one with the bound port.

(5) Have you checked what happens if you press the 'Back' button? In this case (like in the error cases), all threads should be killed.

(6) *Very, very unimportant:* The class is now 580 LOC; ideally it'd be possible to externalize a few things.

**Comment by cr0** [comment]
2) I also thought that we can display a countdown, but I dropped that since it's showing too technical information and might put some pressure on a user.

3) + 4) should be solved with the previous commit.

5) I test that later

**Comment by cr0** [comment]
6) Actually this is not as unimportant as you think since imho it's tough to get used to this class especially with those stupid `Display.getDefault().asyncExec(new Runnable())` calls (really looking forward for Java 8 and lambda expressions, when do we switch? ;))

**Comment by binwiederhier** [comment]
ad (2): Well if there is a countdown and we don't show it, that's even worse I think. Stupid question: Why does there need to be a countdown?

ad (6) "Unimportant" as in "Can do later"; I'm looking forward to Lamdas too :) Let's give it another half year or so? 

Let me know when I need to look at the commit again.

**Comment by binwiederhier** [comment]
Anything to distract me from doing my taxes.

**Comment by cr0** [comment]
Removed the timeout because we dont need it in the GUI. Also extract OAuth code to a helper class to downsize the actual `PluginSettingsPanel`. 

Sorry again for the delay.

**Comment by cr0** [comment]
@binwiederhier, @pimotte could one of you check that it works on other systems/os, too?

**Comment by binwiederhier** [comment]
@cr0 I can check later.

**Comment by pimotte** [comment]
Normal usecase through gui works well. However, if I click cancel upon authenticating, the page shown is a generic error page and I cannot click "Authorize" again, since it is stuck in "waiting...". We should probably catch this in some way.

**Comment by cr0** [comment]
Thanks pim. Never realised that someone will/can do this :D

**Comment by cr0** [comment]
I'm struggeling with an `IllegalAccessException` when stopping undertow from an asynchronous thread:

```
Caused by: java.lang.IllegalAccessError: tried to access method org.syncany.plugins.transfer.oauth.OAuthTokenWebListener.stop()V from class org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper
	at org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper.reset(PluginSettingsPanelOAuthHelper.java:160)
	at org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper.start(PluginSettingsPanelOAuthHelper.java:178)
```
 @binwiederhier Did you have that error before?

**Comment by binwiederhier** [comment]
I get that error by doing Dropbox -> Click [Authorize..] -> *Click okay in browser* -> Click [Back] -> Select "Local" -> Click [Next].

```
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalAccessError: tried to access method org.syncany.plugins.transfer.oauth.OAuthTokenWebListener.stop()V from class org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.operations.gui.GuiOperation.startEventDispatchLoop(GuiOperation.java:215)
	at org.syncany.operations.gui.GuiOperation.execute(GuiOperation.java:102)
	at org.syncany.cli.GuiCommand.execute(GuiCommand.java:48)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.lang.IllegalAccessError: tried to access method org.syncany.plugins.transfer.oauth.OAuthTokenWebListener.stop()V from class org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper
	at org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper.reset(PluginSettingsPanelOAuthHelper.java:160)
	at org.syncany.gui.wizard.PluginSettingsPanel.clearControls(PluginSettingsPanel.java:90)
	at org.syncany.gui.wizard.PluginSettingsPanel.init(PluginSettingsPanel.java:67)
	at org.syncany.gui.wizard.InitPanelController.handleFlow(InitPanelController.java:110)
	at org.syncany.gui.wizard.WizardDialog.handleFlow(WizardDialog.java:249)
	at org.syncany.gui.wizard.WizardDialog.access$000(WizardDialog.java:52)
	at org.syncany.gui.wizard.WizardDialog$2.handleEvent(WizardDialog.java:200)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.syncany.gui.wizard.WizardDialog.open(WizardDialog.java:118)
	at org.syncany.gui.tray.TrayIcon$1.run(TrayIcon.java:140)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	... 10 more
Error: Failed to execute runnable (java.lang.IllegalAccessError: tried to access method org.syncany.plugins.transfer.oauth.OAuthTokenWebListener.stop()V from class org.syncany.gui.wizard.PluginSettingsPanelOAuthHelper)
       Refer to help page using '--help'.
```

After researching this a bit, I found that the compile version of the method does not match the runtime version. So I pulled the newest version of the tm-feature-review-philipp branch and the `stop()` method is private in that:

```
home/pheckel/Coding/Syncany/plugin-gui/syncany-plugin-gui/src/main/java/org/syncany/gui/wizard/PluginSettingsPanelOAuthHelper.java:160: error: stop() has private access in OAuthTokenWebListener
		webListener.stop();
		           ^
/home/pheckel/Coding/Syncany/plugin-gui/syncany-plugin-gui/src/main/java/org/syncany/operations/gui/GuiWebSocketClient.java:170: error: cannot find symbol
		UserTO firstDaemonUser = DaemonConfigHelper.getFirstDaemonUser(daemonConfig);
		                                           ^
  symbol:   method getFirstDaemonUser(DaemonConfigTO)
  location: class DaemonConfigHelper
```

I had no time to fix this, but I think that's definitely the root cause.

**Comment by cr0** [comment]
That's strange since I made that method public on purpose if I remember correctly. I'll fix this (probably not today because the Avengers are waiting for me this evening ;))

**Comment by binwiederhier** [comment]
@cr0 Did you have time to work on this? If not, I'll try to fix this tonight.

**Comment by cr0** [comment]
After browsing through the code on my mobile I think I found the problem. I am confident that I've time tomorrow!

On 3 May 2015 at 21:15:10, Philipp C. Heckel (notifications@github.com) wrote:

@cr0 Did you have time to work on this? If not, I'll try to fix this tonight.

**Comment by binwiederhier** [comment]
Please see https://github.com/syncany/syncany/pull/366#issuecomment-98549166

**Comment by cr0** [comment]
I'm pretty sure that everything now works as expected. But please, feel free to test it, at least one of you.

**Comment by binwiederhier** [comment]
Will do tonight! Awesome!

**Comment by pimotte** [comment]
The scenario I described (cancelling on the request for an authentication token) still has the same unexpected behaviour. The button stays stuck in "Waiting..." and I can only rerequest a token by going back to the plugin selector, selecting another plugin, then going back and reselecting dropbox.

**Comment by binwiederhier** [comment]
I can confirm the behavior. However, it does not crash anymore when choosing another plugin. You can merge this and fix the Cancel/Back bug in another issue.

**Comment by pimotte** [comment]
I am Pim and I support this course of action.

**Comment by binwiederhier** [comment]
Hehe

**Comment by cr0** [comment]
Ok button now gets reenabled when the token extraction failed. Merging once travis is finished.

**Pull request merged**
